Treasure
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #10
Opened 2023-07-06 01:52 UTC by TheShadowOfHassen

This is a PR with all the history for the treasure.

Most of it is made up, because there isn't that much history about barrels of food.

However this is stuff that has to be in the encyclopedia too!

2023-07-09 08:50 UTC, indoptogopt requested changes

2023-07-11 11:48 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/gaia/treasure/food_persian_big.xml
> +        A large display of food, straight from the finest bazars of Persia.
I think the words mean the same thing.

2023-07-11 11:49 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/gaia/treasure/food_persian_small.xml
> +        A display of food, straight from the finest bazars of Persia.
Same as above

2023-07-14 21:10 UTC, TheShadowOfHassen commented
Is this good to be merged?

2023-07-18 11:36 UTC, merged