Merchant template
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #100
Opened 2024-01-13 20:47 UTC by TheShadowOfHassen

2024-01-14 10:50 UTC, indoptogopt requested changes

2024-01-14 10:50 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/template_unit_ship_merchant.xml
> +        Trade on the high seas was a dangerous but lucrative activity. Merchants braved, rough seas, storms, and pirates, while traversing sea lanes that spanned empires. On the way the merchants and
```suggestion
        Trade on the high seas was a dangerous but lucrative activity. Merchants braved, rough seas, storms, and pirates, while traversing sea lanes that spanned empires. On the way the merchants and sailors did not only buy and sell goods but spread news, customs, and ideas, enriching the societies they encountered.
```

2024-01-18 19:58 UTC, TheShadowOfHassen commented
Is this OK to merge?

2024-01-19 21:33 UTC, indoptogopt commented
Yes. What do you think of using this for all merchants?(including the ones we've already written)

2024-01-19 22:25 UTC, TheShadowOfHassen commented
For all merchant ships? It could be. I mean, it's a template so it's already for everything that we don't override with a custom template

2024-01-19 22:25 UTC, merged