Han Wonder
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #101
Opened 2024-01-13 23:39 UTC by TheShadowOfHassen

2024-01-14 10:45 UTC, indoptogopt requested changes

2024-01-14 10:45 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/han/wonder.xml
> +        The Míngtáng Bìyōng, or “Bright Hall” was a temple built in the Imperial palace in the Han capitol of Chang’and. The building’s was constructed directly south of the Han dynasty’s founder, Em
```suggestion
        The Míngtáng Bìyōng, or “Bright Hall” was a temple built in the Imperial Palace in the Han capitol of Chang’and. The building was constructed directly south of the Han dynasty’s founder, Emperor Gaozu, and was symmetrical not only north-south, like most Han buildings, but east-west as well. The Míngtáng Bìyōng was a sight of many religious practices, including ones performed by the emperor himself.
```

2024-01-18 19:58 UTC, TheShadowOfHassen commented
Is this clear to merge?

2024-01-19 21:32 UTC, indoptogopt commented
Yes

2024-01-19 22:26 UTC, merged