imperial ministry and acadamy
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #111
Opened 2024-01-20 18:30 UTC by TheShadowOfHassen

2024-01-21 09:52 UTC, indoptogopt requested changes

2024-01-21 09:52 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/han/academy.xml
> +        The Imperial academy or, Taixue, was the highest place of study in ancient imperial china. The academy taught students Confucianism and literature as well as preparing them to take jobs in th
```suggestion
        The Imperial Academy, or Taixue, was the highest place of study in ancient imperial China. The academy taught students Confucianism and literature as well as preparing them to take jobs in the empire’s government. It was a large school, at its peak having over 30,000 students and faculty.
```

2024-01-21 09:52 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/han/ministry.xml
> +        The Han dynasty had a large bureaucratic force to help efficiently manage the empire’s vast resources. The bureaucrats were organized into nine courts, each put under the charge of an imperia
```suggestion
        The Han dynasty had a large bureaucratic force to help efficiently manage the empire’s vast resources. The bureaucrats were organized into nine courts, each put under the charge of an imperial minister who was responsible of a specific aspect of the government.
```

2024-01-21 09:53 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/han/ministry.xml
> +        The Han dynasty had a large bureaucratic force to help efficiently manage the empire’s vast resources. The bureaucrats were organized into nine courts, each put under the charge of an imperia
I would remove one the "charges"

2024-01-27 13:17 UTC, TheShadowOfHassen commented
Can I merge this?

2024-01-31 15:52 UTC, indoptogopt commented
Yes.

2024-01-31 15:54 UTC, merged