han overview
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #120
Opened 2024-02-04 19:32 UTC by TheShadowOfHassen

2024-02-04 20:27 UTC, indoptogopt requested changes

2024-02-04 20:27 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/special/players/han.xml
> +    <History>The Han dynasty was the second dynasty of imperial China. Founded by a commoner Liu Bang, the empire lasted from 202 BC to AD 220 with a short break in AD 9 when Wang Mang took the thron
```suggestion
    <History>The Han dynasty was the second dynasty of imperial China. Founded by a commoner Liu Bang, the empire lasted from 202 BC to AD 220 with a short break in AD 9 when Wang Mang took the throne. Making it the longest imperial dynasty in Chinese history. The Han dynasty was a period of relative peace, as well as cultural and technological growth and for that reason is considered “the first golden age of China”. The name of today's largest ethnic group in the world, the Han Chinese, derives from this very period. </History>
```

2024-02-07 13:31 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/special/players/han.xml
> +    <History>The Han dynasty was the second dynasty of imperial China. Founded by a commoner Liu Bang, the empire lasted from 202 BC to AD 220 with a short break in AD 9 when Wang Mang took the thron
```suggestion
    <History>
The Han dynasty was the second dynasty of imperial China. Founded by a commoner Liu Bang, the empire lasted from 202 BC to AD 220 with a short break in AD 9 when Wang Mang took the throne. Making it the longest imperial dynasty in Chinese history. The Han dynasty was a period of relative peace, as well as cultural and technological growth, and for that reason is considered “the first golden age of China”. The name of today's largest ethnic group in the world, the Han Chinese, derives from this very period. 
    </History>
```

2024-02-08 15:33 UTC, indoptogopt commented
Yes

2024-02-08 15:50 UTC, merged