Animals2
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #13
Opened 2023-07-14 21:07 UTC by TheShadowOfHassen

More animals!

2023-07-16 08:53 UTC, indoptogopt requested changes

2023-07-16 08:53 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/gaia/fauna_wolf.xml
> +In recent time some people have begun to question if wolves wolves are as aggressive as they are sometimes portrayed, however the coordination in packs allows them to take down animals far bigger tha
```suggestion
       In recent times, some people have begun to question if wolves wolves are as aggressive as they are sometimes portrayed, however, the coordination in packs allows them to take down animals far bigger than themselves, and if the fancy struck them, they could easily kill a gatherer who was working by himself.
```

2023-07-16 08:53 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/gaia/fauna_wolf.xml
> +        While their size and color varied from location, wolves in the ancient world are one species, Canis Lupis. Wolves are canine, predators who run in packs, consisting of extended family. Togeth
```suggestion
        While their size and color varied from location, wolves in the ancient world are one species, Canis Lupis. Wolves are canine predators who run in packs consisting of extended family. Together, they live, hunt and raise the next generation of wolves.
```

2023-07-22 11:47 UTC, TheShadowOfHassen commented
Is this good?

2023-07-22 15:39 UTC, indoptogopt commented
Yes

2023-07-25 11:28 UTC, merged