Macidonian Temple and Wonder
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #132
Opened 2024-03-28 16:16 UTC by TheShadowOfHassen

2024-03-28 20:24 UTC, indoptogopt requested changes

2024-03-28 20:24 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/mace/temple.xml
> +        	The Macedonians still worshiped and sacrificed to the old Greek gods. However after the conquests of Alexander the Great, the pantheon to worship was significantly expanded. Immigrants and t
```suggestion
        	The Macedonians still worshiped and sacrificed to the old Greek gods. However, after the conquests of Alexander the Great, the pantheon to worship was significantly expanded. Immigrants and traders brought their religions all across the empire. A single city could house places of worship for not only Zeus and Athena but gods from Egypt, Persia, and even Yahweh, the God of Israel.
```

2024-03-28 20:24 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/mace/wonder.xml
> +        The Palace of Pella was the home to the Macedonian kings, a sprawling complex covering an area over 90,000 square yards (75,000 square meters). It was constructed by Phillip II, and was Alexa
```suggestion
        The Palace of Pella was the home to the Macedonian kings, a sprawling complex covering an area of over 90,000 square yards (75,000 square meters). It was constructed by Phillip II and was Alexander the Great’s birthplace. Alexander expanded the palace, as did other Macedonian rulers after him. The city of Pella and the palace grew as a prominent location during the Hellenistic age. Sadly, the palace was destroyed in 168 BC after Macedonia was defeated by the Roman Empire.
```

2024-04-06 11:52 UTC, TheShadowOfHassen commented
Is this OK to merge?

2024-04-06 20:29 UTC, indoptogopt commented
Yes

2024-04-06 21:09 UTC, merged