Ptolmic Temple
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #133
Opened 2024-04-06 17:48 UTC by TheShadowOfHassen

2024-04-06 20:48 UTC, indoptogopt requested changes

2024-04-06 20:48 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/ptol/temple.xml
> +    <Hisotry>
```suggestion
    <History>
```

2024-04-06 20:48 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/ptol/temple.xml
> +        While the Greeks upper class worshiped, the Greek deities, or whatever other deities that they discovered their fancy, the Egyptian people were more conservative. The Egyptians kept worshipin
```suggestion
        While the Greek upper class worshiped the Greek deities, or whatever other deities that they discovered their fancy, the Egyptian people were more conservative. The Egyptians kept worshiping the same gods they had been.
```

2024-04-06 20:48 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/ptol/temple.xml
> +        This created an interesting power dichotomy in the Ptolemaic empire that wasn’t in other Hellenistic kingdoms. Unlike in other places, where the kings word was law, the Ptolemaic kings had to
```suggestion
        This created an interesting power dichotomy in the Ptolemaic empire that wasn’t in other Hellenistic kingdoms. Unlike in other places, where the king's word was law, the Ptolemaic kings had to be careful to respect the Egyptian priests and their temples, in fear of the people rising up.
```

2024-04-06 20:48 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/ptol/temple_2.xml
> +        This created an interesting power dichotomy in the Ptolemaic empire that wasn’t in other Hellenistic kingdoms. Unlike in other places, where the kings word was law, the Ptolemaic kings had to
```suggestion
        This created an interesting power dichotomy in the Ptolemaic empire that wasn’t in other Hellenistic kingdoms. Unlike in other places, where the king's word was law, the Ptolemaic kings had to be careful to respect the Egyptian priests and their temples, in fear of the people rising up.
```

2024-04-06 20:48 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/ptol/temple_2.xml
> +        While the Greeks upper class worshiped, the Greek deities, or whatever other deities that they discovered their fancy, the Egyptian people were more conservative. The Egyptians kept worshipin
```suggestion
        While the Greek upper class worshiped the Greek deities, or whatever other deities that they discovered their fancy, the Egyptian people were more conservative. The Egyptians kept worshiping the same gods they had been.
```

2024-04-13 13:32 UTC, TheShadowOfHassen commented
Is this OK to merge?

2024-04-17 20:59 UTC, indoptogopt commented
Yes

2024-04-17 21:11 UTC, merged