General Corral and Feild
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #135
Opened 2024-04-13 16:08 UTC by TheShadowOfHassen

2024-04-17 21:21 UTC, indoptogopt requested changes

2024-04-17 21:21 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/skirmish/structures/default_corral.xml
> +         In ancient times meat was eaten much less frequently than today. It was far better to keep a sheep, for her and milk, or a hen for her eggs. Most often the lower class would eat the meat fro
```suggestion
         In ancient times meat was eaten much less frequently than today. It was far better to keep a sheep, for her milk, or a hen for her eggs. Most often the lower class would eat the meat from temple sacrifices. What wasn’t burnt on the altar was often cooked and shared between the priests and the people.
```

2024-04-17 21:21 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/skirmish/structures/default_field.xml
> +        Grains such as wheat and barely were staples for any ancient society. They were cheap, easy to grow crops that were a staple in the diets of all but the richest individuals.
```suggestion
        Grains such as wheat and barley were staples for any ancient society. They were cheap, easy-to-grow crops that were a staple in the diets of all but the richest individuals.
```

2024-04-20 13:21 UTC, TheShadowOfHassen commented
Is this OK to merge.

2024-04-20 15:53 UTC, indoptogopt commented
Yes

2024-04-20 16:15 UTC, merged