ptolmic wonder
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #137
Opened 2024-04-20 13:19 UTC by TheShadowOfHassen

2024-04-20 13:20 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/structures/ptol/wonder.xml
> +        Construction of the temple began in 237 BC, over the site of a previous temple to Horus. The temple was finished  in 57 BC and had the area of 64,626 square feet (6004 square meters)
```suggestion
        Construction of the temple began in 237 BC, over the site of a previous temple to Horus. The temple was finished  in 57 BC and had an area of 64,626 square feet (6004 square meters)
```

2024-04-20 15:53 UTC, indoptogopt requested changes

2024-04-20 15:53 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/ptol/wonder.xml
> +        Construction of the temple began in 237 BC, over the site of a previous temple to Horus. The temple was finished  in 57 BC and had an area of 64,626 square feet (6004 square meters)
```suggestion
        Construction of the temple began in 237 BC, over the site of a previous temple to Horus. The temple was finished  in 57 BC and had an area of 64,626 square feet (6004 square meters).
```

2024-04-26 18:58 UTC, TheShadowOfHassen commented
Is this Ok to merge?

2024-04-26 20:51 UTC, indoptogopt commented
Yes.

2024-04-26 22:13 UTC, merged