Walls palisades towers
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #27
Opened 2023-08-31 00:40 UTC by TheShadowOfHassen

This is a pr adding walls and towers and turning palisades into a mixin.

2023-08-31 14:13 UTC, indoptogopt requested changes

2023-08-31 14:14 UTC, indoptogopt commented
I don't know to be honest, if putting the mixin after the template (as the parent) works, have you tested it?

2023-09-06 19:09 UTC, TheShadowOfHassen commented
Is this clear to be merged?

2023-09-07 09:54 UTC, indoptogopt commented
Yes

2023-09-09 16:58 UTC, merged