Sparta civic center
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #35
Opened 2023-09-09 17:11 UTC by TheShadowOfHassen

2023-09-09 18:30 UTC, indoptogopt requested changes

2023-09-12 17:40 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/structures/spart/civil_centre.xml
> +        The state of Sparta did not have a monarchy, like many ancient civilizations, nor did they have a republic like Athens, rather they had a mixture of the two forms of government. Sparta did no
```suggestion
        The state of Sparta did not have a monarchy, like many ancient civilizations, nor did they have a republic like Athens, but a mixture of the two forms of government. Sparta did not just have one king, but two, and likewise a council of 28 elders called the ephorate, and an assembly of citizens who could veto laws. This form of government was said to have been instituted by Sparta’s great reformer, Lycurgus. As time went on, however, more power was shifted from the kings to the elected ephorate, until the two kings were little more than war leaders. Remarkably, unlike the pure democracy of Athens, Sparta managed to keep this form of government for around 400 years without corruption.
```

2023-09-16 17:08 UTC, TheShadowOfHassen commented
Is this clear to be merged?

2023-09-16 18:07 UTC, indoptogopt commented
Yeah

2023-09-16 18:11 UTC, merged