Spartan Fishing
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #4
Opened 2023-06-07 17:17 UTC by TheShadowOfHassen

This pull request is the fishing boat and dock for Sparta

2023-06-10 14:32 UTC, indoptogopt requested changes

2023-06-10 14:32 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/spart/dock.xml
> +        While the city of Sparta was not on the coastline, the Spartan empire reached the south-eastern shore of the Peloponnese peninsula and there would certainly be ports along the sea. Plutarch s
```suggestion
        While the city of Sparta was not on the coastline, the Spartan empire reached the south-eastern shore of the Peloponnese peninsula and there would certainly be ports along the sea. Plutarch says that the Spartans were engaged in sea trade, that is until the reforms of Lycurgus did away with it. History tells us that the Spartans had a navy. It was never as powerful, however, as Athens'.
```

2023-06-10 14:32 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/units/spart/ship_fishing.xml
> +        Fish were caught on the south-eastern shore of the Peloponnese peninsula and possibly also along the river of Evrótas, that lead to the city Sparta.
```suggestion
        Fish were caught on the south-eastern shore of the Peloponnese peninsula and possibly also along the river Evrótas, that lead to the city of Sparta.
```

2023-06-13 11:03 UTC, TheShadowOfHassen commented
Is there anything else I need to change before merging?

2023-06-13 19:43 UTC, indoptogopt commented
You can merge it.

2023-06-13 21:08 UTC, merged