Fortresses and sparta wonder
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #41
Opened 2023-09-19 18:16 UTC by TheShadowOfHassen

2023-09-20 08:20 UTC, indoptogopt requested changes

2023-09-20 08:20 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/spart/wonder.xml
> +        Hieron tēs Artemidos Orthias or the Sanctuary of Artemis Orthias was a place where many religious festivals were held, including a coming of age rite where Spartan boys would try to steal som
```suggestion
        Hieron tēs Artemidos Orthias, or the Sanctuary of Artemis Orthias, was a place where many religious festivals were held, including a coming-of-age rite where some boys would try to steal cheese from the altar, and other boys would try to catch them and beat them.
```

2023-09-20 08:20 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/spart/wonder.xml
> +        Archaeological evidence is scarce, but it is thought that originally this site was dedicated to a goddess named Orthias, who seemed to be a fertility goddess who watched over children. Over t
```suggestion
        Archaeological evidence is scarce, but it is thought that originally this site was dedicated to a goddess named Orthias, who seemed to be a fertility goddess who watched over children. Over time, however, her character was closer and closer associated to the Greek godess Artemis, and later inscriptions read Artemis Orthias before eventually just reading Artemis.
```

2023-09-20 08:20 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/spart/wonder.xml
> +        The sanctuary had been destroyed and rebuilt over the years, but its use was continued to into the fourth century AD.
```suggestion
        The sanctuary had been destroyed and rebuilt over the years, but its use was continued into the fourth century AD.
```

2023-09-20 08:20 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/units/han/siege_ram.xml
> +<Entity parent="encyclopedia/encyclopedia_siege_ram|encyclopedia/encyclopedia_siege_ram|template_unit_siege_ram">
```suggestion
<Entity parent="encyclopedia/encyclopedia_siege_ram|template_unit_siege_ram">
```

2023-09-26 00:36 UTC, TheShadowOfHassen commented
Is this clear to be merged?

2023-09-26 07:56 UTC, indoptogopt commented
Have you not commited the one suggestion on purpose?

2023-09-26 11:14 UTC, TheShadowOfHassen commented
Oops didn't see it. Clear now?

2023-09-26 16:51 UTC, indoptogopt commented
Yes

2023-09-26 20:15 UTC, merged