stable
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #43
Opened 2023-09-22 01:24 UTC by TheShadowOfHassen

2023-09-22 06:47 UTC, indoptogopt requested changes

2023-09-22 06:47 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/spart/stable.xml
> +        Calvary for a long time was a weak spot in Sparta’s military. For the longest time their only force was the hippeus, a force of 300 mounted infantry who would guard the kings and perform in r
```suggestion
        Cavalry for a long time was a weak spot in Sparta’s military. For the longest time, their only force was the Hippeis, a force of 300 mounted infantry who would guard the kings and perform in religious ceremonies. In 424 BC, the Spartans started putting those deemed unfit to fight on horses to ride as scouts. However, the amount of Spartans who were cavalry only ever amounted to only 60 per mora (Xenophon wrote that a mora contained around 600 men). Sparta did also bolster their ranks with mercenaries.
```

2023-09-26 00:39 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/structures/spart/stable.xml
> +        Cavalry for a long time was a weak spot in Sparta’s military. For the longest time, their only force was the Hippeis, a force of 300 mounted infantry who would guard the kings and perform in
```suggestion
        Cavalry for a long time was a weak spot in Sparta’s military. For the longest time, their only force was the Hippeis, a force of 300 mounted infantry who would guard the kings and perform in religious ceremonies. In 424 BC, the Spartans started putting those deemed unfit to fight on horses to ride as scouts. The amount of Spartans who were cavalry only ever amounted to only 60 per mora (Xenophon wrote that a mora contained around 600 men). Sparta also bolstered their ranks with mercenaries.
```

2023-09-26 00:39 UTC, TheShadowOfHassen commented
is this clear to be merged?

2023-09-26 07:02 UTC, indoptogopt commented
Yes

2023-09-26 11:14 UTC, merged