Sparta summary
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #47
Opened 2023-10-02 20:36 UTC by TheShadowOfHassen

2023-10-03 07:02 UTC, indoptogopt requested changes

2023-10-03 07:02 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/special/players/spart.xml
> +        Spartan culture was obsessed with military training and excellence, all spartan boys were drafted into rigorous training at age seven, and their military service lasted until they were sixty.
```suggestion
        Spartan culture was obsessed with military training and excellence, all Spartan boys were drafted into rigorous training at age seven, and their military service lasted until they were sixty. All trades were done by their serfs, the Helots.
```

2023-10-03 07:02 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/special/players/spart.xml
> +        Spartans lived a strict and minimalistic lifestyle, separate from many of the other civilization, due to reforms such as iron money, which were given by Lycurgus.
```suggestion
        Spartans lived a strict and minimalistic lifestyle, separate from many of the other civilizations, due to reforms such as iron money, which were given by Lycurgus, the legendary Spartan lawgiver.
```

2023-10-10 23:33 UTC, TheShadowOfHassen commented
Can I merge something?

2023-10-11 07:39 UTC, indoptogopt commented
Yes you can merge it

2023-10-12 20:55 UTC, merged