Trees Pull Request
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #5
Opened 2023-06-07 17:19 UTC by TheShadowOfHassen

Ok, this is a huge pull request for all of 0 A.D.'s trees(gaia/tree) and also apples from the fruit category.

2023-06-07 20:18 UTC, s0600204 reviewed
A lot of these read as descriptions (for which the `<Description>` tag would be better) rather than histories. Anyway...

* Be consistent with abbreviations. In some places you've used `ft`, in others, the full unit `feet`.
* Be consistent with capitalisations. e.g. `Autumn`/`autumn`, `Acorn`/`acorn`, `Summer`/`summer`, `Oak`/`oak`, `Fall`/`fall` (where it refers to the season, not something... falling).
* Use apostrophes where applicable, rather than single quotation marks. (`'` not `’`).
* The possessive form of `it` is `its`, not `it's`.
* Various entries have a missing space prior to an opening parenthesis. (`text(text` -> `text (text`).
* Various entries have a double space between words mid-sentence.

2023-06-07 20:18 UTC, s0600204 commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/poplar_lombardy_autumn.xml
> +        It is Autumn and this Poplars' leaves are fading yellow and soon will fall to the ground.
`Poplars'` -> `Poplar's`

2023-06-07 20:32 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/oak_holly_autumn.xml
> +        The Holly Oak(Quercus ilex)i s commonly called the Holm oak is a fascinating Oak which does not shed its leaves in winter. It grows along Southern Europe and into Asia. It grows up to 100 fee
Got It.

2023-06-07 20:34 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/pine_maritime.xml
> +       The Maritime Pine, (Pinus pinaster) as the name says, can survive in coastal locations. The Maritime Pine is even resistant to salt water. It can grow up to 130 feet, however, in exposed condi
Yep you are right.

2023-06-07 20:36 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/banyan.xml
> +        The Banyan Tree or Ficus benghalensis is a unique fig tree. They start as a small epiphyte that grows on a host tree before suffocating and taking it’s place. The tree has huge, low spreading
Got it.

2023-06-07 20:37 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/oak_aut.xml
> +        It is autum now and this oak's leaves are turning colors and begining to fall. Clearly, it isn't a Holm Oak
Got it

2023-06-07 20:38 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/temperate_autumn.xml
> +       The once green leaves of these temperate, template trees have faded into a variety of orange and red hues. Soon the trees will shed their leaves and be ready to weather the coming winter.
It's a joke. I researched 70 some trees I get to make a few jokes.

2023-06-07 20:38 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/tropic_rainforest.xml
> +        These tree’s wide canopies of leaves will not fall off at autumn. Also these trees will be given at least 100 inches of rain a year.
Yep.

2023-06-07 20:38 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/oak.xml
> +        The species Oak (Quercus) is one of the most recognizable trees on earth. There are many varieties of the tree from the more standard English Oak to the Holm Oak, which is an evergreen. While
it should be acorn

2023-06-07 20:39 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/acacia.xml
> +        Commonly known as thorn trees, the Acacia, part of the Mimosa subfamily, grows in a variety of open habitats, varying from tropical to subtropical. While 900 of the 1,200 trees live in Austra
Thanks, stuff like this is the most helpful. I'm changing it to tree's species

2023-06-07 20:51 UTC, TheShadowOfHassen commented
> A lot of these read as descriptions (for which the `<Description>` tag would be better) rather than histories. Anyway...
> 
> * Be consistent with abbreviations. In some places you've used `ft`, in others, the full unit `feet`.
> * Be consistent with capitalisations. e.g. `Autumn`/`autumn`, `Acorn`/`acorn`, `Summer`/`summer`, `Oak`/`oak`, `Fall`/`fall` (where it refers to the season, not something... falling).
> * Use apostrophes where applicable, rather than single quotation marks. (`'` not `’`).
> * The possessive form of `it` is `its`, not `it's`.
> * Various entries have a missing space prior to an opening parenthesis. (`text(text` -> `text (text`).
> * Various entries have a double space between words mid-sentence.

There is a description tag?!? No one told me. I haven't looked hard, but the description tag looks like it's been used mostly for in game descriptions, so this is more history than it is gameplay relevant description.

2023-06-10 18:23 UTC, indoptogopt requested changes

2023-06-10 18:23 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/euro_birch.xml
> +        The European Birch or Silver Birch is a hearty tree, able to survive the harsh weather in Scandinavia as the warm Mediterranean cost. It grows up to 100 ft, and its bark is white to silver an
```suggestion
        The European Birch or Silver Birch is a hearty tree, able to survive the harsh weather in Scandinavia as the warm Mediterranean cost. It grows up to 100 feet, and its bark is white to silver and has serrated, triangular leaves. 
```

2023-06-10 18:23 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/palm_palmyra.xml
> +        The Palmyra Palm (Borassus flabellifer) is also known by many other names. It grows up to 98 ft tall and produces palmyra fruit which is usually eaten unripe and tastes like coconut.
```suggestion
        The Palmyra Palm (Borassus flabellifer) is also known by many other names. It grows up to 98 feet tall and produces palmyra fruit which is usually eaten unripe and tastes like coconut.
```

2023-06-10 18:23 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/poplar_lombardy_autumn.xml
> +        It is Autumn and this Poplar's leaves are fading yellow and soon will fall to the ground.
```suggestion
        It is autumn and this poplar's leaves are fading yellow and soon will fall to the ground.
```

2023-06-10 18:23 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/maple_autumn.xml
> +        It is Fall and this maple tree's leaves are turning crimson.
```suggestion
        It is fall and this maple tree's leaves are turning crimson.
```

2023-06-10 18:23 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/oak_holly.xml
> +        The Holly Oak(Quercus ilex) is also called the Holm Oak. It is a fascinating Oak which does not shed its leaves in winter. It grows along Southern Europe and into Asia. It grows up to 100 fee
```suggestion
        The Holly Oak (Quercus ilex) is also called the Holm Oak. It is a fascinating Oak which does not shed its leaves in winter. It grows along Southern Europe and into Asia. It grows up to 100 feet tall.
```

2023-06-10 18:23 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/gaia/tree/oak_holly_autumn.xml
> +        The Holly Oak(Quercus ilex) is also called the Holm Oak. It is a fascinating Oak which does not shed its leaves in winter. It grows along Southern Europe and into Asia. It grows up to 100 fee
```suggestion
        The Holly Oak (Quercus ilex) is also called the Holm Oak. It is a fascinating Oak which does not shed its leaves in winter. It grows along Southern Europe and into Asia. It grows up to 100 feet tall.
```

2023-06-13 11:20 UTC, TheShadowOfHassen commented
We are capitalizing seasons like Fall, Autumn and Winter, so those changes can't happen.

I think I got everything else.

Is this clear to be merged?

2023-06-13 19:35 UTC, indoptogopt commented
Yes, you can merge it.

2023-06-13 21:11 UTC, merged