Farming greek
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #50
Opened 2023-10-07 20:06 UTC by TheShadowOfHassen

Changes some of Sparta's farming into mixins for Athens and also adding Athens farming.

2023-10-08 16:04 UTC, indoptogopt requested changes

2023-10-08 16:04 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/mixins/encyclopedia/encyclopedia_greek_coral.xml
> +        The mountains of Greece aren’t the best land for raising large animals like cows. However, the grass on the mountains were perfect grazing grounds for goats and sheep. Chickens were also rais
```suggestion
        The mountains of Greece aren’t the best land for raising large animals like cows. However, the grass on the mountains were perfect grazing grounds for goats and sheep. Chickens were also raised around houses, and their eggs were gathered.
```

2023-10-21 18:18 UTC, TheShadowOfHassen commented
Is this clear to merge?

2023-10-21 18:47 UTC, indoptogopt commented
Yes.

2023-10-21 18:47 UTC, merged