Athenian temple and wonder
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #55
Opened 2023-10-15 00:50 UTC by TheShadowOfHassen

2023-10-15 00:50 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/structures/athen/temple.xml
> +        Athens was extremely religious. The city state itself was named in honor Athena after she, as the Greek myth says, created the olive tree for them. She was their primary deity. That said, Ath
```suggestion
        Athens was extremely religious. The city state itself was named in honor  of Athena after she, as the Greek myth says, created the olive tree for them. She was their primary deity. That said, Athens worshiped all gods of the Greek pantheon and many besides.
```

2023-10-15 00:51 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/structures/athen/wonder.xml
> +        Unfortunately, the Parthenon has not aged well. Over the years the structure has been converted both into a Greek Orthodox church, a Mosque, and an ammunition dump, that exploded, destroyed t
```suggestion
        Unfortunately, the Parthenon has not aged well. Over the years the structure has been converted both into a Greek Orthodox church, a Mosque, and an ammunition dump, that exploded, destroyed the building's center. It still stands on the Athenian acropolis, a ruin with most of its statues stolen or destroyed.
```

2023-10-15 10:23 UTC, indoptogopt requested changes

2023-10-15 10:23 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/athen/temple.xml
> +        Perhaps, one of the most amusing stories of Athenian was at the battle of Marathon where Athens, facing superior odds, vowed to sacrifice a she-goat to Artemis for every Persian they slew. Th
```suggestion
        Perhaps one of the most amusing stories of Athenian was at the Battle of Marathon, where Athens, facing superior odds, vowed to sacrifice a she-goat to Artemis for every Persian they slew. They killed 6,400 Persians. They did not have that many she-goats on hand, so decided that they would sacrifice 500 goats per year, and did so for nearly a century.
```

2023-10-15 10:23 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/athen/wonder.xml
> +        The Parthenon was the most magnificent temple in all of Ancient Greece. It was built after the Greco-Persian, replacing an older structure that was destroyed by the Persians. It was decorated
```suggestion
        The Parthenon was the most magnificent temple in all of Ancient Greece. It was built after the Greco-Persian Wars, replacing an older structure that was destroyed by the Persians. It was decorated with many sculptures, the biggest being the Athena Parthenose. Constructed by Pheidias, the Athena Parthenose was around 38 feet (11.5 meters) tall and plated with gold and ivory.
```

2023-10-15 10:23 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/athen/wonder.xml
> +        Unfortunately, the Parthenon has not aged well. Over the years the structure has been converted both into a Greek Orthodox church, a Mosque, and an ammunition dump, that exploded, destroyed t
```suggestion
        Unfortunately, the Parthenon has not aged well. Over the years, the structure has been converted both into a Greek Orthodox church, a mosque, and an ammunition dump that exploded and destroyed the building's center. It still stands on the Athenian acropolis, a ruin with most of its statues stolen or destroyed.
```

2023-10-28 20:10 UTC, TheShadowOfHassen commented
Is this OK to merge?

2023-10-31 17:55 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/structures/athen/wonder.xml
> +        Unfortunately, the Parthenon has not aged well. Over the years, the structure has been converted both into a Greek Orthodox church, a mosque, and an ammunition dump that exploded and destroye
```suggestion
        Unfortunately, the Parthenon has not aged well. Over the years, the structure has been converted both into a Greek Orthodox church, a mosque, and an ammunition dump that exploded and destroyed the building's center. It still stands on the Athenian acropolis, but it is now a ruin, with most of its statues stolen or destroyed.
```

2023-11-04 19:21 UTC, merged