Athenian Civic Center
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #63
Opened 2023-10-28 21:13 UTC by TheShadowOfHassen

2023-10-30 15:38 UTC, indoptogopt commented
Could you look over the text again? I cant  understand some sentences or make out what you're trying to say

2023-10-31 17:39 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/structures/athen/civil_centre.xml
> +    	Originally, Athens was ruled by a line of kings, descendants of Theseus. However, like many other Greek City. However, Athenian has undoubtedly become the most famous. The democracy had many ite
```suggestion
    	Originally, Athens was ruled by a line of kings. But, like many other Greek City states, Athens became a republic. Athenians democracy had many iterations, with many people reforming its laws.

2023-10-31 17:39 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/structures/athen/civil_centre.xml
> +    	Democracy in ancient Athens was semi stable, every so often a tyrant would overthrow it, usually to the oppression of the populace. To try to protect themselves against it, there became the prac
```suggestion
    	Democracy in ancient Athens was semi stable, every so often a tyrant would overthrow it, usually to the oppression of the populace. To try to protect themselves against it, the Athenians began the practice of ostracism. Every year the Athenian people who decide whether to conduct an ostracism. If so, the citizens of Athens would write on shards of broken pottery the name of a politician who they thought was getting too much power. Whoever had the most votes was exiled for ten years.
```

2023-10-31 17:39 UTC, TheShadowOfHassen commented
Is that better?

2023-11-01 15:12 UTC, indoptogopt requested changes

2023-11-01 15:12 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/athen/civil_centre.xml
> +    	Originally, Athens was ruled by a line of kings. But, like many other Greek City states, Athens became a republic. Athenians democracy had many iterations, with many people reforming its laws.
```suggestion
    	Originally, Athens was ruled by a line of kings, but, like many other Greek city states, eventually became a republic. Athens' democracy had many iterations, with many people reforming its laws such as Solon and Cleisthenes.
```

2023-11-01 15:12 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/athen/civil_centre.xml
> +    	The primary actors in the democracy were the Athenian citizens, men over the age of twenty. Citizens were appointed, elected, or chosen by lot to positions of magistrate, tribunal, or council an
```suggestion
    	The primary actors in the democracy were the Athenian citizens, men over the age of twenty. Citizens were appointed, elected, or chosen by lot to positions of magistrate, tribunal, or council and could attend the assembly, which was the primary place of government.
```

2023-11-01 15:12 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/athen/civil_centre.xml
> +    	Democracy in ancient Athens was semi stable, every so often a tyrant would overthrow it, usually to the oppression of the populace. To try to protect themselves against it, the Athenians began t
```suggestion
    	Democracy in ancient Athens was semi-stable, every so often a tyrant would overthrow it, usually to the oppression of the populace. To try to protect themselves against it, the Athenians began the practice of ostracism. Every year the Athenian people decided whether to conduct an ostracism. If so, the citizens of Athens would write on shards of broken pottery the name of a politician who they thought was getting too much power. Whoever had the most votes was exiled for ten years.
```

2023-11-01 15:13 UTC, indoptogopt commented
> Is that better?

Yup, thank you

2023-11-04 19:05 UTC, TheShadowOfHassen commented
Thank _you_ for looking it over.

2023-11-08 01:47 UTC, merged