Athennian Overview
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #72
Opened 2023-11-15 14:14 UTC by TheShadowOfHassen

Athenian Overview + an edit for the spartan overview

2023-11-15 14:15 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/special/players/athen.xml
> +        Ancient Athens rose and fell as an imperial power until 330 BC when they lost the Battle of Chaeronea to King Phillip II of Macedonia. While after that it never rose again to power, Athens st
```suggestion
        Ancient Athens rose and fell as an imperial power until 330 BC, when they lost the Battle of Chaeronea to King Phillip II of Macedonia. While after that it never rose again to power, Athens still was renown for its learning and its scholars were well sought out as teachers.</History>
```

2023-11-15 16:09 UTC, indoptogopt requested changes

2023-11-15 16:09 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/special/players/athen.xml
> +        The Greek city state Athens is famous remembered a famed center for the arts, learning, and philosophy, as well as one of the earliest forms of democracy. That wasn't to say that they weren't
```suggestion
        The Greek city-state of Athens is remembered a famed center for the arts, learning, and philosophy, as well as one of the earliest forms of democracy. That wasn't to say that they weren't warriors. Athens at its height had one of the most powerful navys in the ancient world and through conquering and colinizing built a vast empire.
```

2023-11-15 16:09 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/special/players/athen.xml
> +        Ancient Athens rose and fell as an imperial power until 330 BC, when they lost the Battle of Chaeronea to King Phillip II of Macedonia. While after that it never rose again to power, Athens s
```suggestion
        Ancient Athens rose to an imperial power after defeating the invading Persians twice in the early fifth century BC, and fell in 330 BC, when they lost the Battle of Chaeronea to King Phillip II of Macedonia. While after that it never rose again to power, Athens still was renown for its learning and its scholars were well sought out as teachers.</History>
```

2023-11-15 16:15 UTC, TheShadowOfHassen commented
Very good addition!

2023-11-24 00:32 UTC, TheShadowOfHassen commented
Is this OK to merge?

2023-11-24 07:48 UTC, indoptogopt commented
Yes

2023-11-24 12:45 UTC, merged