han house
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #89
Opened 2023-12-20 02:00 UTC by TheShadowOfHassen

2023-12-20 02:02 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/structures/han/house.xml
> +        Houses in the ancient Han period were, like everywhere else in the world, separated into two different kinds. The squat, straw thatched houses of the poor. Or the sprawling compounds of the w
```suggestion
        Houses in the ancient Han period were, like everywhere else in the world, separated into two different kinds. The squat, straw thatched houses of the poor. Or the sprawling compounds of the wealthy.
```

2023-12-20 02:02 UTC, TheShadowOfHassen commented on 0-ad-history-mod-package/simulation/templates/structures/han/house.xml
> +        In ancient china the houses of the rich were, like a great deal of other things, constructed with an extreme function of order, almost even to extreme. The many buildings of the rich mansions
```suggestion
        In Ancient China the houses of the rich were, like a great deal of other things, constructed with an extreme function of order, almost even to extreme. The many buildings of the rich mansions were built running north-south. And  were laid out symmetrically around a main building, a style known as Siheyuan. The separate buildings were designated for different branches of the extended family. For example, a wealthy merchant would have a separate building for his parents,  another for his children and their families and more for his wives,  servants. Other buildings could be shrines, or places to store food or prepare it. The buildings were connected by courtyards and the entire compound was surrounded by a wall.
```

2023-12-21 17:19 UTC, indoptogopt requested changes

2023-12-21 17:19 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/han/house.xml
> +        Houses in the ancient Han period were, like everywhere else in the world, separated into two different kinds. The squat, straw thatched houses of the poor. Or the sprawling compounds of the w
```suggestion
        Houses in the ancient Han period were, like everywhere else in the world, separated into two different kinds. The squat, straw-thatched houses of the poor. Or the sprawling compounds of the wealthy.
```

2023-12-21 17:19 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/structures/han/house.xml
> +        In Ancient China the houses of the rich were, like a great deal of other things, constructed with an extreme function of order, almost even to extreme. The many buildings of the rich mansions
```suggestion
        In Ancient China the houses of the rich were, like a great deal of other things, constructed with an extreme function of order, almost even to extreme. The many buildings of the rich mansions were built running north-south. And were laid out symmetrically around a main building, a style known as Siheyuan. The separate buildings were designated for different branches of the extended family. For example, a wealthy merchant would have a separate building for his parents, another for his children and their families and more for his wives and servants. Other buildings could be shrines, or places to store food or prepare it. The buildings were connected by courtyards, and the entire compound was surrounded by a wall.
```

2023-12-28 00:10 UTC, TheShadowOfHassen commented
Is this clear to merge?

2023-12-28 20:17 UTC, indoptogopt commented
Yes

2023-12-28 21:06 UTC, merged