Han women
TheShadowOfHassen/0-ad-history-encyclopedia-mod pull request #94
Opened 2023-12-29 00:27 UTC by TheShadowOfHassen

2023-12-29 12:07 UTC, indoptogopt requested changes

2023-12-29 12:07 UTC, indoptogopt commented on 0-ad-history-mod-package/simulation/templates/units/han/support_female_citizen.xml
> +        While they did have a degree of freedom, the Han dynasty was in no way perfect. Like many places in ancient times Han women could not own land (and consequentially didn’t have to pay taxes) A
```suggestion
        While they did have a degree of freedom, the Han dynasty was in no way perfect in this regard. Like many places in ancient times, in Han China women could not own land (and consequentially didn’t have to pay taxes). And women were expected to stay in either of the household of their father or their husband. Even worse, it wasn’t unheard of for a wealthy Han man to take a second wife or concubine, which often caused fierce jealousy.
```

2024-01-05 21:23 UTC, TheShadowOfHassen commented
Is this clear to be merged?

2024-01-06 20:15 UTC, indoptogopt commented
Yes

2024-01-06 22:07 UTC, merged